import { Activity, BrainCircuit, Gauge, LockKeyhole, ShieldCheck, Sparkles, TrendingDown, TrendingUp } from 'lucide-react'
import type { IntelligenceResponse, RatesResponse } from '../types'
import { formatINR, formatNumber, formatSignedINR, formatSignedPercent } from '../utils/format'
import { InsightCard } from './InsightCard'

type Props = { intelligence: IntelligenceResponse | null; rates: RatesResponse | null; loading: boolean }

export function InsightsDashboard({ intelligence, rates, loading }: Props) {
  const ready = intelligence?.status === 'READY'
  const score = intelligence?.trend.score ?? 0
  const Trend = score >= 0 ? TrendingUp : TrendingDown
  const goldChange = intelligence?.momentum.gold_change ?? null
  const forecast = intelligence?.forecast
  return <div className="dashboard-view insights-view">
    <div className="dashboard-intro"><div><span className="section-kicker">DECISION SUPPORT</span><h2>Signal over noise.</h2><p>Transparent market intelligence built from verified observations.</p></div><span className="dashboard-source"><ShieldCheck size={14} /> No generated history</span></div>
    <InsightCard intelligence={intelligence} loading={loading} />
    <div className="intelligence-grid">
      <section className="panel intelligence-trend-panel"><div className="dashboard-panel-title"><span className="section-kicker">TREND ENGINE</span><h2>Directional signal</h2><Trend size={17} /></div><div className="intelligence-hero-value"><span className="intelligence-badge"><Trend size={16} /> {ready ? intelligence.trend.label : 'Unavailable'}</span><strong>{ready && intelligence.trend.score !== null ? `${intelligence.trend.score > 0 ? '+' : ''}${intelligence.trend.score}` : '—'}</strong><small>Signal score</small></div><p className="intelligence-description">{intelligence?.trend.description || 'The model needs more observations before it can describe the selected market.'}</p><div className="insight-reasons"><div><span>Observed move</span><strong>{formatSignedINR(goldChange)} <small>{formatSignedPercent(intelligence?.momentum.gold_change_percent)}</small></strong></div><div><span>Observed direction</span><strong>{ready ? intelligence.trend.label : 'Waiting for data'}</strong></div><div><span>Data source</span><strong>{intelligence?.source || rates?.source || 'No source yet'}</strong></div></div><div className="intelligence-source"><LockKeyhole size={13} /> {intelligence?.data_points ?? 0} observations · model is indicative, not financial advice</div></section>
      <section className="panel intelligence-forecast-panel"><div className="dashboard-panel-title"><span className="section-kicker">FORECAST RANGE</span><h2>Next daily observation</h2><Gauge size={17} /></div>{ready && forecast ? <><div className="forecast-pair"><div className="forecast-quote"><span>24K GOLD / 10g</span><strong>{formatINR(forecast.gold_24k_10g)}</strong></div><div className="forecast-quote gst-forecast"><span>999 GOLD + GST / 10g</span><strong>{formatINR(forecast.gold_999_with_gst_10g)}</strong></div></div><div className="forecast-label">24K expected range</div><div className="forecast-band"><span>{formatINR(forecast.lower_bound)}</span><i><b style={{ left: '42%' }} /></i><span>{formatINR(forecast.upper_bound)}</span></div><div className="forecast-label">999 + GST expected range</div><div className="forecast-band gst-band"><span>{formatINR(forecast.gold_999_with_gst_lower_bound)}</span><i><b style={{ left: '58%' }} /></i><span>{formatINR(forecast.gold_999_with_gst_upper_bound)}</span></div><div className="forecast-meta"><span>Confidence<strong>{forecast.confidence}</strong></span><span>Window<strong>{intelligence.data_points} points</strong></span></div></> : <div className="intelligence-empty"><Sparkles size={20} /><strong>Building the evidence base</strong><span>{intelligence?.source_note || 'A reliable forecast will appear once enough observations are available.'}</span></div>}</section>
      <section className="panel intelligence-metrics-panel"><div className="dashboard-panel-title"><span className="section-kicker">MARKET METRICS</span><h2>Momentum and risk</h2><Activity size={17} /></div><div className="metric-list"><div><span><Activity size={13} /> Gold momentum</span><strong>{formatSignedPercent(intelligence?.momentum.gold_change_percent)}</strong></div><div><span><Activity size={13} /> Silver momentum</span><strong>{formatSignedPercent(intelligence?.momentum.silver_change_percent)}</strong></div><div><span><Gauge size={13} /> Gold volatility</span><strong>{ready ? `${formatNumber(intelligence.volatility.gold_percent)}%` : '—'}</strong></div><div><span><BrainCircuit size={13} /> Method</span><strong>{ready ? 'Transparent' : 'Waiting'}</strong></div></div><p className="method-note">{intelligence?.method || 'Trend, momentum, realized volatility, and linear forecast calculations.'}</p></section>
    </div>
  </div>
}
